hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}_dino
  job:
    chdir: true
  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "metric.json"
model_name: "ViT-B/16"
prompt_template: "an aerial photograph of a {} airplane."
use_dino: true
dino_weights: "/mnt/datasets/dinov2_vitb14.pth"

batch_size: 128
initial_increment: 10
increment: ${initial_increment}
scenario: "class"
dataset: "fgvc_aircraft"
num_workers: 4
train_batch_size: 64
epochs: 15
lr: 0.001
fp16: false
seed: 2
milestones: [4,10]
beta: 2
mix_bias: 0.6
threshold: 0.55
shrinkage: true
